version: 2.1

orbs:
  ruby: circleci/ruby@1.0.4
  node: circleci/node@3.0.1

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.0-node
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    environment:
      RAILS_ENV: test
    executor: ruby/default
    steps:
      - checkout
      - run: bundle --version
      - run: node --version
      - run: yarn --version
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run Rails tests
          command: bundle exec rails test
