version: 2.1

orbs:
  ruby: circleci/ruby@1.0.4
  node: circleci/node@3.0.1

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.0-node
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: dashwork_test
          POSTGRES_PASSWORD: flickthepaperwork
    environment:
      RAILS_ENV: test
    executor: ruby/default
    steps:
      - checkout
      - ruby/install-deps
      - node/install-packages:
        pkg-manager: yarn
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database setup
          command: bundle exec rails db:schema:load --trace
      - run:
          name: Run Rails tests
          command: bundle exec rails test
