product_name: Dashwork

icons:
  apps: fas fa-th
  assets: fas fa-car-side
  back: fas fa-arrow-left
  books: fas fa-book-reader
  calendar: fas fa-calendar-alt
  companies: fas fa-briefcase
  complete: fas fa-check-circle
  contacts: fas fa-address-book
  create: fas fa-plus
  custom_fields: fas fa-clipboard-list
  delete: fas fa-trash
  edit: fas fa-edit
  equipment: fas fa-truck
  export: fas fa-cloud-download-alt
  form_templates: fas fa-box
  forms: fas fa-file-signature
  go_to: fas fa-arrow-right
  help: fas fa-question-circle
  import: fas fa-upload
  log_in: fas fa-sign-in-alt
  notes: fas fa-sticky-note
  personal_log: fas fa-book
  personal_log_review: fas fa-binoculars
  profile: fas fa-user-circle
  projects: fas fa-project-diagram
  reviews: fas fa-bullhorn
  settings: fas fa-wrench
  sign_out: fas fa-power-off
  sign_up: fas fa-user-plus
  star: far fa-star
  starred: fas fa-star
  tags: fas fa-tags
  tasks: fas fa-tasks
  tenant_settings: fas fa-building
