product_name: Dashwork

icons:
  apps: fa-solid fa-th
  appearance: fa-solid fa-paint-brush
  back: fa-solid fa-arrow-left
  calendar: fa-solid fa-calendar-alt
  companies: fa-solid fa-briefcase
  complete: fa-solid fa-check-circle
  contacts: fa-solid fa-address-book
  create: fa-solid fa-plus
  custom_fields: fa-solid fa-clipboard-list
  delete: fa-solid fa-trash
  edit: fa-solid fa-edit
  ellipsis: fa-solid fa-ellipsis-h
  export: fa-solid fa-cloud-download-alt
  file: fa-regular fa-file
  folder: fa-solid fa-folder
  go_to: fa-solid fa-arrow-right
  help: fa-solid fa-question-circle
  import: fa-solid fa-upload
  log_in: fa-solid fa-sign-in-alt
  notes: fa-solid fa-sticky-note
  personal_log: fa-solid fa-book
  personal_log_review: fa-solid fa-binoculars
  profile: fa-solid fa-user-circle
  projects: fa-solid fa-project-diagram
  settings: fa-solid fa-wrench
  sign_out: fa-solid fa-power-off
  sign_up: fa-solid fa-user-plus
  star: fa-regular fa-star
  starred: fa-solid fa-star
  tags: fa-solid fa-tags
  tasks: fa-solid fa-tasks
  tenant_settings: fa-solid fa-building
  wiki: fa-solid fa-graduation-cap
  write: fa-solid fa-pen-fancy
