product_name: Dashwork

icons:
  calendar: fas fa-calendar-alt
  companies: fas fa-briefcase
  contacts: fas fa-address-book
  equipment: fas fa-truck
  form_templates: fas fa-box
  forms: fas fa-file-signature
  notes: fas fa-sticky-note
  projects: fas fa-project-diagram
  tasks: fas fa-tasks
  back: fas fa-arrow-left
  apps: fas fa-th
  create: fas fa-plus
  delete: fas fa-trash
  edit: fas fa-edit
  settings: fas fa-wrench
  sign_out: fas fa-power-off
