product_name: Dashwork

icons:
  apps: fas fa-th
  appearance: fas fa-paint-brush
  back: fas fa-arrow-left
  calendar: fas fa-calendar-alt
  companies: fas fa-briefcase
  complete: fas fa-check-circle
  contacts: fas fa-address-book
  create: fas fa-plus
  custom_fields: fas fa-clipboard-list
  delete: fas fa-trash
  edit: fas fa-edit
  ellipsis: fas fa-ellipsis-h
  export: fas fa-cloud-download-alt
  file: far fa-file
  folder: fas fa-folder
  go_to: fas fa-arrow-right
  help: fas fa-question-circle
  import: fas fa-upload
  log_in: fas fa-sign-in-alt
  notes: fas fa-sticky-note
  personal_log: fas fa-book
  personal_log_review: fas fa-binoculars
  profile: fas fa-user-circle
  projects: fas fa-project-diagram
  settings: fas fa-wrench
  sign_out: fas fa-power-off
  sign_up: fas fa-user-plus
  star: far fa-star
  starred: fas fa-star
  tags: fas fa-tags
  tasks: fas fa-tasks
  tenant_settings: fas fa-building
  wiki: fas fa-graduation-cap
  write: fas fa-pen-fancy
